### ISSUE TITLE
 Exception Type KeyError. Args: ('_action',)

### ISSUE THREAD

**Issue by ciremoussadia** [darwinex/dwx-zeromq-connector#100]
Hello,
it's almost a week I'm having this error for almost all commands.
```
Exception Type KeyError. Args:
('_action',)
```
This is an example
```

In [1]: from DWX_ZeroMQ_Connector_v2_0_1_RC8 import DWX_ZeroMQ_Connector

In [2]: dwx = DWX_ZeroMQ_Connector()
[INIT] Ready to send commands to METATRADER (PUSH): 32768
[INIT] Listening for responses from METATRADER (PULL): 32769
[INIT] Listening for market data from METATRADER (SUB): 32770

In [3]: dwx._DWX_MTX_NEW_TRADE_()

Exception Type KeyError. Args:
('_action',)
In [4]: 
```

**Comment by elvinex** [comment]
Hi,
I can't replicate this error. As you can see in `_generate_default_order_dict()` the action is set to

**Comment by ciremoussadia** [comment]
@elvinex yes I've the latest version of both and I don't define a custom action.

**Comment by ciremoussadia** [comment]
@elvinex auto-trading was deactivated

**Comment by elvinex** [comment]
Ok, thanks for letting us know. It it still a small bug in the API because normally you should get a 
`{'_response': 'TRADING_IS_NOT_ALLOWED__ABORTED_COMMAND'}`
response if auto-trading is turned off. I found the reason and made a small update. Now it should give the correct error message.

**Comment by ciremoussadia** [comment]
Wow @elvinex awesome I'm glad I help you find that. Thanks for the update.
