### ISSUE TITLE
unable to receive data//DWX_ZeroMQ_Connector_v2_0_1_RC8//_DWX_MTX_SUBSCRIBE_MARKETDATA_

### ISSUE THREAD

**Issue by 280791011** [darwinex/dwx-zeromq-connector#102]
Hello guys,
Thank you very much for maintaining this project.
I'm facing a problem at early stage. 
![bug1](https://user-images.githubusercontent.com/73998434/98240127-ed855280-1fa3-11eb-96e4-b9448c3226a6.png)
![bug2](https://user-images.githubusercontent.com/73998434/98240134-efe7ac80-1fa3-11eb-971f-dbf9abcce2e5.png)
It's okay to send orders into MT4.
MT4 Server is able to send out data.
I'm not able to receive data locally via Python.

Could you help me to figure out the problem? thanks.

**Comment by elvinex** [comment]
Hi,
did you run the track prices function? 

`_zmq._DWX_MTX_SEND_TRACKPRICES_REQUEST_(['EURUSD'])`

You probably did because else I think MT4 would not send prices. 
I just ran subscribe+trackprices and it works, so I can't reproduce the error.

**Comment by 280791011** [comment]
> Hi,
> did you run the track prices function?
> 
> `_zmq._DWX_MTX_SEND_TRACKPRICES_REQUEST_(['EURUSD'])`
> 
> You probably did because else I think MT4 would not send prices.
> I just ran subscribe+trackprices and it works, so I can't reproduce the error.

Hi, elvinex, 
Thank you for your reply.
May I know if you are using version 2.0.2 or 2.0.1?
because there's no function called _DWX_MTX_SEND_TRACKPRICES_REQUEST_() in DWX_ZeroMQ_Connector_v2_0_1_RC8.py

thanks.

**Comment by 280791011** [comment]
![bug3](https://user-images.githubusercontent.com/73998434/98789780-c0222400-243d-11eb-9014-0bde8c6ab17b.png)
when I print self._Market_Data_DB, it returns empty.
no idea how I can make it work..

**Comment by elvinex** [comment]
The function name has an underscore at the end like this `_DWX_MTX_SEND_TRACKPRICES_REQUEST_()`. 

https://github.com/darwinex/dwx-zeromq-connector/blob/master/v2.0.1/python/api/DWX_ZeroMQ_Connector_v2_0_1_RC8.py

**Comment by 280791011** [comment]
> The function name has an underscore at the end like this `_DWX_MTX_SEND_TRACKPRICES_REQUEST_()`.
> 
> https://github.com/darwinex/dwx-zeromq-connector/blob/master/v2.0.1/python/api/DWX_ZeroMQ_Connector_v2_0_1_RC8.py

I see. this file in your link is different from what I downloaded. 
seems it's been updated.
let me have a try.
Thank you elvinex~~

**Comment by 280791011** [comment]
> > The function name has an underscore at the end like this `_DWX_MTX_SEND_TRACKPRICES_REQUEST_()`.
> > https://github.com/darwinex/dwx-zeromq-connector/blob/master/v2.0.1/python/api/DWX_ZeroMQ_Connector_v2_0_1_RC8.py
> 
> I see. this file in your link is different from what I downloaded.
> seems it's been updated.
> let me have a try.
> Thank you elvinex~~

still doesn't work.. still empty.

**Comment by elvinex** [comment]
Did you delete and replace all old files? Source code and libraries?

**Comment by 280791011** [comment]
> Did you delete and replace all old files? Source code and libraries?

I'm trying so.
actually I didn't know there was an update because it's still 2.0.1.

I will update after I refresh everything.

thanks.

**Comment by elvinex** [comment]
Running this in ipython console worked for me:
```from DWX_ZeroMQ_Connector_v2_0_1_RC8 import DWX_ZeroMQ_Connector
dwx = DWX_ZeroMQ_Connector()
dwx._DWX_MTX_SEND_TRACKPRICES_REQUEST_(['EURUSD'])
dwx._DWX_MTX_SUBSCRIBE_MARKETDATA_('EURUSD')```

**Comment by 280791011** [comment]
> Running this in ipython console worked for me:
> 
> ```
> from DWX_ZeroMQ_Connector_v2_0_1_RC8 import DWX_ZeroMQ_Connector
> dwx = DWX_ZeroMQ_Connector()
> dwx._DWX_MTX_SEND_TRACKPRICES_REQUEST_(['EURUSD'])
> dwx._DWX_MTX_SUBSCRIBE_MARKETDATA_('EURUSD')
> ```

Yes.  _DWX_MTX_SEND_TRACKPRICES_REQUEST_([]) is a new function in new file.
And I udpated new DWX_ZeroMQ_Server_v2.0.1_RC8.mq4 as well.
And now it works~~~
Thank you very much elvinex~~~

**Comment by elvinex** [comment]
Ok, great to hear that it worked eventually. :)
