### ISSUE TITLE
_zmq._DWX_MTX_SEND_HIST_REQUEST_ returns None

### ISSUE THREAD

**Issue by BoxInCode** [darwinex/dwx-zeromq-connector#106]
Hi! I'm trying to get the Historical Data to use in a MA calculation but I cannot iterate through or get any type of operation on the function, I tried to use https://github.com/darwinex/dwx-zeromq-connector/issues/67 solution, but I didn't figure it out.
I tried to use the _self_._zmq._get_response_() with sleep() but no change at all.

I have a print on this issue.

![Screenshot from 2020-12-11 23-17-54](https://user-images.githubusercontent.com/70492456/101963693-3cf41980-3c07-11eb-946b-67de30ee1177.png)
![Screenshot from 2020-12-11 23-18-03](https://user-images.githubusercontent.com/70492456/101963697-3f567380-3c07-11eb-9675-79c2bcde79fa.png)

Thank you very much in advance! I'm new to Algo trading and Python Programming, I have a course of both matters and working every day into the code, so I'm getting the grip of it, thank you y'all! Be safe! :)

**Comment by elvinex** [comment]
Hi,
the function _DWX_MTX_SEND_HIST_REQUEST_()  only sends the request. It does not return anything (None). 
You could print/parse _get_response_() for the response from MT4.
