### ISSUE TITLE
2020.12.16 17:14:35.387	Cannot load 'C:\Users\client_user\AppData\Roaming\MetaQuotes\Terminal\D6B27BE5FE154CBBDBCA690D2E70609D\MQL4\Libraries\libzmq.dll' [193]

### ISSUE THREAD

**Issue by ZixiSu** [darwinex/dwx-zeromq-connector#107]
```
2020.12.16 17:14:35.387	Cannot load 'C:\Users\client_user\AppData\Roaming\MetaQuotes\Terminal\D6B27BE5FE154CBBDBCA690D2E70609D\MQL4\Libraries\libzmq.dll' [193]

2020.12.16 17:14:35.355	Expert DWX_ZeroMQ_Server_v2.0.1_RC8 USDCHF,H4: loaded successfully


```
![image](https://user-images.githubusercontent.com/6142004/102312324-99b65200-3fc2-11eb-8e93-8302e19284df.png)
It is smiling when I drag the EA in the VPS

![image](https://user-images.githubusercontent.com/6142004/102312350-a8046e00-3fc2-11eb-9e4d-2242cb5bcc22.png)
The error messages
The two pictures are all from VPS

I can run DWX_ZeroMQ_Server_v2_0_1_RC8 in my local computer, but as I need to run it 24 hours, I bought one VPS, and I have downloaded and installed the latest Visual C++ runtime (2015). But I still cannot run it in the VPS.

My question is do I need to change the HOSTNAME from * to something else?

**Comment by Friedrichowski** [comment]
Make sure that you have installed the 32bit version of Visual C++ runtime.

**Comment by ZixiSu** [comment]
Its a UAC problem, I should use admin rights to install the MT4, problem solved

**Comment by crluna** [comment]
https://www.youtube.com/playlist?list=PLv-cA-4O3y97vTpghgRqiPBjmpgWskYDl

Have a look at that video and the vids in that playlist
