### ISSUE TITLE
How can I change the port defined in DWX_ZeroMQ_Connector()

### ISSUE THREAD

**Issue by ZixiSu** [darwinex/dwx-zeromq-connector#108]
class DWX_ZeroMQ_Connector():

    """
    Setup ZeroMQ -> MetaTrader Connector
    """
    def __init__(self, 
                 _ClientID='dwx-zeromq',    # Unique ID for this client
                 _host='localhost',         # Host to connect to
                 _protocol='tcp',           # Connection protocol
                 _PUSH_PORT=32778,          # Port for Sending commands
                 _PULL_PORT=32779,          # Port for Receiving responses
                 _SUB_PORT=32771,           # Port for Subscribing for prices
                 _delimiter=';',
                 _pulldata_handlers = [],   # Handlers to process data received through PULL port.
                 _subdata_handlers = [],    # Handlers to process data received through SUB port.
                 _verbose=True,             # String delimiter
                 _poll_timeout=1000,        # ZMQ Poller Timeout (ms)
                 _sleep_delay=0.001,        # 1 ms for time.sleep()
                 _monitor=False):           # Experimental ZeroMQ Socket Monitoring

In class DWX_ZeroMQ_Connector(), can we change the _PUSH_PORT = 32778 to 32768?

**Comment by ZixiSu** [comment]
> Hi,
> 
> It should work if you also change the port number in the parameters of the MT4 EA so that both are referring to the same ports.

May I ask what the port number range I can use? a random number? like32555?

**Comment by elvinex** [comment]
You can use `netstat -ab` in windows powershell to see used ports. Most ports above 10,000 should be fine.
