### ISSUE TITLE
How to set Maximum orders for one symbol?

### ISSUE THREAD

**Issue by ZixiSu** [darwinex/dwx-zeromq-connector#111]
![image](https://user-images.githubusercontent.com/6142004/103900165-976f8f80-514b-11eb-975a-c6f24fdb7fa2.png)
Hi team,

In the EA, we can define the maximum lots we can enter, but if I want to define for every symbol, the maximum order is 2.
For example, the maximum orders for all is 10 lots, for EURUSD maximum is 2 lots, XAUUSD maximum is 2 lots, XAGUSD maximum is 2 lots, AUDUSD maximum is 2 lots, GBPUSD maximum is 2 lots.

How can change the EA

**Comment by elvinex** [comment]
Hi,
To clean up the issues, we decided to close issues with general questions that have been inactive for a long while. 

Your idea is of course possible, but would require some work. I would start by learning how you can count the positions of a specific symbol in mql, for example here:
https://www.mql5.com/en/forum/128351
And then add your code to the `DWX_OpenOrder()` function.
