### ISSUE TITLE
Publish_MarketData input parameter not available con MT4

### ISSUE THREAD

**Issue by oliverm91** [darwinex/dwx-zeromq-connector#117]
I can't see the input parameter Publish_MarketData when I drag the expert to the chart.
DWX_ZeroMQ_Server_v2.0.1_RC8

![image](https://user-images.githubusercontent.com/7751221/105931503-190b5c80-602a-11eb-9899-bb1cf9123da8.png)

**Comment by oliverm91** [comment]
added `extern` to variable `Publish_MatketData` in line 42 to solve it.

**Comment by elvinex** [comment]
Hi,
Thanks for raising this issue. After the latest update the `Publish_MarketData` variable is set automatically on subscribing to symbols. So you don't have to set it manually yourself.
