### ISSUE TITLE
DWX_ZeroMQ_Server_v2.0.1_RC8.mq4 won't reply with more than 12 orders

### ISSUE THREAD

**Issue by jackshankenburg** [darwinex/dwx-zeromq-connector#13]
I'm placing orders in EURUSD and once I send a 13th order it appears the MQL4 expert server stops replying to the python connector's request to get open orders.

DWX_ZeroMQ_Connector_v2_0_1_RC8.py prints None after a 13th order has been sent.

Is anyone else able to replicate?

**Comment by integracore2** [comment]
Hi @jackshankenburg ,

We weren't able to replicate this behaviour in our tests unforntunately.. could you please confirm if you're still experiencing this issue?

If yes, kindly provide any logs from Experts and Journals that could assist us in debugging this further.

Thanks!
