### ISSUE TITLE
Issues receiving MetaTrader responses when executing code from a script

### ISSUE THREAD

**Issue by matkiller333** [darwinex/dwx-zeromq-connector#134]
Hello everyone,
So here is my problem, I am working on a web scraper to perform trades depending on information gathered on the internet.
However, when I try executing requests inside a python script, such as _zmq.DWX_MTX_GET_ALL_OPEN_TRADES() I get no answers from the server and cannot retrieve any information under _zmq._Market_Data_DB or _zmq._History_DB.

Moreover, if I try to open an order with zmq.DWX_MTX_NEW_TRADE(order) I get the Resource timeout.. please try again. error.
(MS VC++ is downloaded and up to date; verbose = True)

If using a python shell, however, I can pass orders that are received by MetaTrader4 and I am getting the expected output from other functions.

Therefore, this is leading me to believe that maybe there is a problem receiving responses from MetaTrader4 when using a script instead of a shell command. Any idea on how to fix this would be really appreciated.
Thank you.

Running python 3.9 on Windows 10, Using MetaTrader4 and coding in PyCharm

**Comment by TheSnowGuru** [comment]
try pytrader :) works better
