### ISSUE TITLE
Get Rsi indicator value from meta trader to zmq connector 

### ISSUE THREAD

**Issue by MinaAdelAbdu** [darwinex/dwx-zeromq-connector#135]
@integracore2 
Hi
I use zero MQ and I want to get  value of RSI indicator from Meta Trader to my strategy client by python

**Comment by VladPerervenko** [comment]
Hi,
Why would you need to pull indicator data from the terminal if Python has several indicator libraries? For example : pandas-ta, ta, ta-py .
The calculation will be faster than a transaction from the terminal.
