### ISSUE TITLE
Account Info

### ISSUE THREAD

**Issue by arashag** [darwinex/dwx-zeromq-connector#137]
Hi.

I need to extract account info including balance, equity, etc which are crucial in money management in trading. Could you please add these functions to the ZMQ connector?

Thanks.

**Comment by teddywaweru** [comment]
Hi Arash.
I have a pull request in place concerning [this](https://github.com/darwinex/dwx-zeromq-connector/pull/136). I've also received your personal email concerning saving the output to a dict, but I wanted to get the basic functionality in place first, then proceed to altering the data handling functions.
For now you could access the results from the `_thread_data_output` object, immediately after caalling the account info request.

**Comment by arashag** [comment]
Thanks.

**Comment by elvinex** [comment]
Thank you for adding a function to get account data! We merged the pull request.

**Comment by teddywaweru** [comment]
@elvinex thanks for that. I think the implementation can be improved by utilizing proper variable tags on the EA, but I had paused on contributing, since it had been stated that the repository won't be supported anymore. If Darwinex has rolled back on this decision, I can dive back in.

**Comment by elvinex** [comment]
Thanks for the offer. I don't think Darwinex has rolled back on this decision. I will probably continue to review issues and pull requests from time to time, but I have very little time available for this project.
