### ISSUE TITLE
DWX_ZeroMQ_Server_v2.0.1_RC8.mq4 to .mq5

### ISSUE THREAD

**Issue by mariosuences** [darwinex/dwx-zeromq-connector#14]
I have changed the .mql4 to .mql5 to be able of work with mt5 but there are around 100 error when  compile

**Comment by integracore2** [comment]
Hi @mariosuences ,

You cannot simply rename a .mql4 to a .mql5 unfortunately... they are two different programming languages in the eyes of MetaTrader.

The DWX ZeroMQ Connector EA is written for MetaTrader 4, and will not work on MetaTrader 5 without modification for MQL5.

Hope that helps answer your question.
