### ISSUE TITLE
Invalid Trade Volume

### ISSUE THREAD

**Issue by jimmylai-hk** [darwinex/dwx-zeromq-connector#142]
I follow exactly all the required instructions from the youtube video .

https://www.youtube.com/watch?v=U2VdXdm2qlM&list=PLv-cA-4O3y97vTpghgRqiPBjmpgWskYDl&index=7

and I got the follow errors when I use the following Python command.

_zmq._DWX_MTX_NEW_TRADE_()

{'_action': 'EXECUTION', '_response': '131', 'response_value': 'invalid trade volume'}

I also try different Python command with smaller lot size.  However, the error message is the same.

_zmq._DWX_MTX_SEND_COMMAND_(_action='OPEN', _type=0,
                            _symbol='EURUSD', _price=0.0,
                            _SL=25, _TP=50, _comment="Python-to-MT",
                            _lots=0.001, _magic=123456, _ticket=0)

**Comment by TobiahRex** [comment]
If you haven't already resolved, i think your size is possibly too small?

1 Lot = 100,000 -> 1.00
1 Mini-Lot = 10,000 -> 0.1
1 micro-Lot = 1,000 -> 0.01

I've never seen nor heard of a "Micro-Micro-Lot" = 100 -> 0.001
