### ISSUE TITLE
Custom indicator data

### ISSUE THREAD

**Issue by 2knarf** [darwinex/dwx-zeromq-connector#15]
Hi, How can I send custom indicator data to zmq?

**Comment by integracore2** [comment]
Hi @2knarf ,

It depends on what you're trying to achieve by doing that.

For example,

1) You could retrieve data for say the RSI indicator applied to an asset e.g. EURUSD,  via ZeroMQ from MetaTrader.

2) If you were calculating an indicator outside of MetaTrader and using it to perform trading actions, you wouldn't need to send that data to MetaTrader, you could simply send orders to execute based on such an external indicator.

Hope the above helps!

**Comment by 2knarf** [comment]
Hi. Thanks for the reply. I want to achieve #1. Can you give me some guidelines for This?

**Comment by integracore2** [comment]
Hi @2knarf ,

To achieve point 1, you'd need to copy one of the DWX_() methods in the MQL EA and edit it to include your desired functionality.

We don't unfortunately have the resources at the present time to provide specific programming support in MQL and Python, but the code is fairly self-explanatory so hopefully should be fairly straightforward for you to implement.

All the best!
