### ISSUE TITLE
New Trade SL and TP price values

### ISSUE THREAD

**Issue by pwerspire** [darwinex/dwx-zeromq-connector#17]
Hi,

I need to open new trades passing SL and TP that are price values instead of points. There is any way of doing this?

I tried to pass it in DWX_MTX_NEW_TRADE but the values are not accepted, it's supposed to be only points from what I understood.

Thanks

**Comment by integracore2** [comment]
Hi @pwerspire ,

Yes that is correct. We've kept SL and TP defined in points to enable any available assets in MetaTrader to be used from the Python client, with no dependency on the digit profile of the asset in question.

You can of course modify this behaviour to prices by modifying the EA to suit your purposes, no worries!
