### ISSUE TITLE
[Question] Backtest

### ISSUE THREAD

**Issue by edge7** [darwinex/dwx-zeromq-connector#19]
Is it possible to make it work also for backtesting?

**Comment by edge7** [comment]
I figured it out, myself!
Are PR accepted?

**Comment by integracore2** [comment]
Hi @edge7 ,

Thank you for your interest!

Yes, Pull Requests are certainly permitted, but we reserve the right to approve / reject depending on the nature of the request.

Please feel free to submit your PR and we'll review it as soon as we can.

Thanks!

**Comment by CornerStone12** [comment]
Was this merged and/or are there perhaps any steps available on how to do it?

**Comment by Boscop** [comment]
@edge7 Can you please share the solution you found for backtesting EAs that are ZMQ clients? :)
