### ISSUE TITLE
Run other EA together with the dwx connector EA

### ISSUE THREAD

**Issue by quantnlp** [darwinex/dwx-zeromq-connector#21]
Hi,

Thanks a lot for the great work and I got it worked correctly.

However, the connector only works if I ONLY run ONE EA (DWX_ZeroMQ) on MT4. The DWX EA will  not work if I have other EA running.

Is it possible to run DWX with other EAs on the same MT4? It would be great if we can.

Thanks,
Frank

**Comment by integracore2** [comment]
Hi @quantnlp 

Thank you for your kind comments! Much appreciated.

We haven't been able to reproduce this issue unfortunately.. one possibility that comes to mind is that the other EA is possibly using the same Magic Number as the DWX EA?

If you could provide more details as regards what the other EA is doing, we may be able to dig further and diagnose this better.

Thanks!
