### ISSUE TITLE
Save output to a Python variable instead of printing on screen

### ISSUE THREAD

**Issue by quantnlp** [darwinex/dwx-zeromq-connector#23]
Hi,

I was trying to record all open trades called by `trades = _zmq._DWX_MTX_GET_ALL_OPEN_TRADES_()`

However, the variable "trades" is a NoneType. Is there any way that I can store the output from the connector to a Python variable so that I can write it to csv, instead of printing on screen?

Thanks,
Frank

**Comment by integracore2** [comment]
Hi @quantnlp ,

Thank you for your query.

If you review the code, you'll notice that any of the _DWX_ functions in the script store outputs in a variable called self._thread_data_output, i.e. a call to the function does not "return" anything.

To access the output after a call to the functions, you can either directly access self._thread_data_output, or use the getter/setter functions self._get_response_() and self._set_response_() depending on your particular usecase.

Hope this helps!
