### ISSUE TITLE
getting list of pending, filled and rejected orders

### ISSUE THREAD

**Issue by radulylaszlo1** [darwinex/dwx-zeromq-connector#25]
Hi All,
Is there a way to get the list of pending,filled, and rejected orders in python?
Also list of Instruments would be great.
Thank you.

**Comment by integracore2** [comment]
Hi @radulylaszlo1 ,

Thank you for your interest!

In MetaTrader 4, orders available for reporting are either in state OPEN (in the market) or CLOSED (historical).

The _DWX_GET_OPEN_TRADES_() function in the Python script enables you to see all orders currently open.

However, when you attempt to execute an order and let's say it doesn't get filled, MetaTrader 4 will respond via the MQL EA provided in this project, with an error message describing what happened.

Hope this helps answer your question.
