### ISSUE TITLE
Autentication

### ISSUE THREAD

**Issue by Deeptradingfx** [darwinex/dwx-zeromq-connector#27]
there is any solution like token something like that to make my mt4 server safety coz any one with endpoint url can open trade to my account i couldnt find on library how to ser new public key any one could give a exemplo

**Comment by integracore2** [comment]
Hi @Deeptradingfx ,

Yes, we're addressing this as per the discussion in this issue:
https://github.com/darwinex/dwx-zeromq-connector/issues/30

We'll keep you posted!
