### ISSUE TITLE
[REQUEST] Get list of all instruments from MetaTrader Terminal

### ISSUE THREAD

**Issue by radulylaszlo1** [darwinex/dwx-zeromq-connector#28]
Hi,

Is there a way to get the list of all available instruments?
Thanks.

**Comment by integracore2** [comment]
Hi @radulylaszlo1 ,

Great question!

We'll add this as a feature for future releases, but in the meantime if you'd like to implement something custom for yourself, you would need to use the following MQL4 functions:

1) `SymbolsTotal()` - which returns the number of available symbols in the Terminal, setting the "selected" argument to True or False will return symbols in MarketWatch or all available symbols respectively.

2) `SymbolName()` - which takes an integer index as the symbol's position in the list, and returns the name of the symbol (e.g. EURUSD, etc etc)
