### ISSUE TITLE
cannot capture every instrument

### ISSUE THREAD

**Issue by radulylaszlo1** [darwinex/dwx-zeromq-connector#29]
It tried to record every instrument of a broker called FXCM just to see if there is any arbitrage opportunity. (looks like there isn't)
I was able to record only 54 instruments out of 94. For me it looks like zeroqm cannot see CFDs like 'USB30YUSD' or "DAX-SEP19."
I can see that MT4 is publishing 'USB30YUSD' and it is also included in the Publish_Symbols[94] list in the mq4 file.
Is it possible that zeromq can only see instruments with 6 characters?

**Comment by Deeptradingfx** [comment]
> It tried to record every instrument of a broker called FXCM just to see if there is any arbitrage opportunity. (looks like there isn't)
> I was able to record only 54 instruments out of 94. For me it looks like zeroqm cannot see CFDs like 'USB30YUSD' or "DAX-SEP19."
> I can see that MT4 is publishing 'USB30YUSD' and it is also included in the Publish_Symbols[94] list in the mq4 file.
> Is it possible that zeromq can only see instruments with 6 characters?


 a workaround   call the symble as string and set it array   string variable = "symbolname";

**Comment by rnjema** [comment]
How was this resolved?
