### ISSUE TITLE
Migration to MQL5

### ISSUE THREAD

**Issue by brunobuger** [darwinex/dwx-zeromq-connector#32]
Hi everyone!
I would like to migrate the connector to MQL5 (dwx-zeromq-connector/v2.0.1/mql4/DWX_ZeroMQ_Server_v2.0.1_RC8.mq4) .. I'm willing to pay for.
Unfortunately, here in Brazil all the exchanges only work with MT5...

Thanks!

**Comment by integracore2** [comment]
Hi @brunobuger ,

Thank you for your interest in the project 🙂 

Yes, we’ve already been working on an MQL5 version for Darwinex (www.darwinex.com) traders but don’t yet have a release date unfortunately.

Development is already complete, but testing to ensure everything is fluid and operational is what we still require time for.

We’ll keep everyone posted as to our progress - no worries.

Thanks again!

**Comment by brunobuger** [comment]
Awesome @integracore2 ! When it's ready, I can contribute with the Java Client example!
I am looking forward to it.

**Comment by brunobuger** [comment]
> Hi @brunobuger ,
> 
> Thank you for your interest in the project 🙂
> 
> Yes, we’ve already been working on an MQL5 version for Darwinex ([www.darwinex.com](http://www.darwinex.com)) traders but don’t yet have a release date unfortunately.
> 
> Development is already complete, but testing to ensure everything is fluid and operational is what we still require time for.
> 
> We’ll keep everyone posted as to our progress - no worries.
> 
> Thanks again!

@integracore2  Last thing, if you need a help to test.. I would like to be an early adopter

**Comment by integracore2** [comment]
That’s great to hear @brunobuger ! 🙂 

Absolutely, we’ll keep you posted.

**Comment by falberto** [comment]
Hey!
Any news on this?

thank you!

**Comment by diogopublio** [comment]
hey guys, any update here ?
