### ISSUE TITLE
'TRADING_IS_NOT_ALLOWED__ABORTED_COMMAND'

### ISSUE THREAD

**Issue by efeveret01** [darwinex/dwx-zeromq-connector#35]
Trying to use both the _DWX_MTX_CLOSE_ALL_TRADES_() and _DWX_MTX_NEW_TRADE_(), at first they were working now they send the following message:

{'_response': 'TRADING_IS_NOT_ALLOWED__ABORTED_COMMAND'}

**Comment by integracore2** [comment]
Hi @efeveret01 ,

This error is raised in either or both of the following scenarios:

1) "Allow live trading" is unchecked in your EA Inputs tab.

2) The "Autotrading" button at the top of your MT4 terminal is set to disabled.

Kindly enable the two to resolve the issue.
