### ISSUE TITLE
MT4 'cannot open file' error with DWX_ZeroMQ_Server_v2.0.1_RC8.mq4

### ISSUE THREAD

**Issue by gitobu56** [darwinex/dwx-zeromq-connector#39]
Hi. I just copied the DWX_ZeroMQ_Server_v2.0.1_RC8.mq4 into my Experts folder as instructed but the MT4 wont open the EA and keeps shouting the error 'cannot open file +(path to said file)' in the Experts logs.
I'm not sure what I did wrong. Can someone help?

**Comment by integracore2** [comment]
Hi @gitobu56 ,

This appears to be an issue related to how you've possibly installed the project.. let's dig deeper.

Please reply with the following:

1) Your Expert logs

2) Confirmation that you've got the latest code in this repository, and have followed the README instructions (very important to follow everything in there to ensure correct functionality).

Hope this helps.

**Comment by gitobu56** [comment]
Thanks. Finally got it to work. I had failed to compile it in the Meta editor.Please include the instruction "Click compile button " for newer users. 
kind regards
