### ISSUE TITLE
Broker Error 129: Invalid Price on FXCM

### ISSUE THREAD

**Issue by Pejhan** [darwinex/dwx-zeromq-connector#44]
hello,
This error has been mentioned before but it seems there has been no cure for it but I keep getting the error when I attempt to execute a New Trade using the Default Order Dict.
 simply:

import DWX_ZeroMQ_Connector_v2_0_1_RC8 as dwx

_zmq = dwx.DWX_ZeroMQ_Connector()
_zmq._generate_default_order_dict()
_zmq._DWX_MTX_NEW_TRADE_()

**Comment by gregnwosu** [comment]
as mentioned previously it is usually due to having incorrect libraries installed, check in particular that you have MS Visual Studio C++ Runtime 2015 installed on the machine. Also check that libsodium is properly installed.

**Comment by Pejhan** [comment]
Ive checked all the steps required to get the thing running but no progress so far.

**Comment by Pejhan** [comment]
I havent had such a problem with other functions that Ive used so far but the seems to be a lagging problem with committing a new trade to the market.
also Im using the FXCM MetaTrader4 if its of any significance.

**Comment by integracore2** [comment]
Hi @Pejhan ,

The behaviour you're describing is not an issue with the code, it is a broker-level issue.

The dwx-zeromq-connector project has been developed for and tested solely on Darwinex MT4 terminals, and as such, we cannot assist you with debugging activity on other broker terminals.

**Comment by Pejhan** [comment]
Thanks for the help @integracore2 & @gregnwosu. Ill try other options and investigate further on your solutions.

**Comment by Pejhan** [comment]
Thanks for the help @integracore2 & @gregnwosu. Ill try other options and investigate further on your solutions.

**Comment by Pejhan** [comment]
Thanks for the help @integracore2 & @gregnwosu. Ill try other options and investigate further on your solutions.

**Comment by gregnwosu** [comment]
im actually having the same issue with IG , I'm using [this guide](https://www.iexpertadvisor.com/how-to-debug-expert-advisors-metatrader-4/) to debug the EA to figure out what is happening

**Comment by Pejhan** [comment]
@integracore2 thank you. I switched to the DxMT4 platform and everythings in order.
@gregnwosu Thank you for introducing this guide is its gonna help me later on.

**Comment by gregnwosu** [comment]
which platform is DxMT4 is that darwinex?

**Comment by Pejhan** [comment]
yes you can download it at : https://download.mql5.com/cdn/web/tradeslide.trading.tech/mt4/darwinex4setup.exe
