### ISSUE TITLE
Getting OHLC Data from DWX_MTX_SEND_MARKETDATA_REQUEST

### ISSUE THREAD

**Issue by Pucal** [darwinex/dwx-zeromq-connector#47]
Is there any way to get OHLC data from  DWX_MTX_SEND_MARKETDATA_REQUEST instead of only the close

**Comment by foxriver011** [comment]
please answer this

**Comment by foxriver011** [comment]
> Is there any way to get OHLC data from DWX_MTX_SEND_MARKETDATA_REQUEST instead of only the close

hey Pucal
you can see DWX_ZeroMQ_Server_v2.0.1_RC8.mq4 file then check DWX_GetData function and modify it 

for example if you want openPrice you can change CopyClose to CopyOpen

I with it will be useful for you

**Comment by integracore2** [comment]
Hi @Pucal ,

@foxriver011 's solution is indeed correct 🙂 

We are working to make market data I/O more robust between Python and MetaTrader at the present time. We'll keep you posted!
