### ISSUE TITLE
dev branch

### ISSUE THREAD

**Issue by grayskripko** [darwinex/dwx-zeromq-connector#50]
Instead of warning users to avoid using the latest version and creating a separate folder, why don't create a dev branch?

**Comment by integracore2** [comment]
Hi @grayskripko ,

Completely agree with you 🙂 

This project initially started out as a place to store example scripts. Interest from more than a few users lead to iterative versioning, that we now need to organize.

This is a priority and already being addressed - thank you for your feedback though, much appreciated!
