### ISSUE TITLE
push socket problem

### ISSUE THREAD

**Issue by foxriver011** [darwinex/dwx-zeromq-connector#51]
hey
when I change monitor variable == true
I got result below:
[KERNEL] NO HANDSHAKE ON PUSH SOCKET.. Cannot SEND data
please help me to fix this error.

**Comment by integracore2** [comment]
Hi @foxriver011 ,

The socket monitoring feature is experimental (stated as such in the code).

This is not an error. It is a message indicating that your client application was unsuccessful in handshaking for I/O with MetaTrader.

For now, simply setting `_monitor=False` will override this behaviour.
