### ISSUE TITLE
MT4 having issues importing the libzmq.dll file - Please help 

### ISSUE THREAD

**Issue by issamBD** [darwinex/dwx-zeromq-connector#52]
I’m having issues starting the ZMQ server, according to the logs it won’t initilazed because MT4 is not able to import the libzmq.dll file

![2cc8729600a72b90c2c0bb1beaaaa706d42fc02e](https://user-images.githubusercontent.com/55186957/67862998-65b07100-fb23-11e9-8fbd-dadba631f8c2.png)

Info:
-I’m using windows 8 64 bit
-AutoTrading and DLL import are both activated
-The dependencies are all imported to the libraries folder

**Comment by Saruntaey** [comment]
Have you try installing Visual c++?
Here is the link. https://www.microsoft.com/en-US/download/details.aspx?id=48145

**Comment by integracore2** [comment]
Hi @issamBD ,

As stated in the README, Visual C++ Runtime Libraries are a mandatory requirement for using LibZMQ in this project.

Please watch the following video for more information:
https://www.youtube.com/watch?v=7aAsFZ_r5zU&t=1236s

**Comment by issamBD** [comment]
installing Visual c++ didn't solve the issue. Also I updated my operating system to windows 10 and went through the whole process from the beguining and unfortunately the issue still stands

**Comment by issamBD** [comment]
SOLVED by uninstalling Visual C++ Runtime x64 version I had on my computer and install the 32 bit version.
