### ISSUE TITLE
 [KERNEL] NO HANDSHAKE ON PUSH SOCKET.. Cannot SEND data

### ISSUE THREAD

**Issue by ildeb** [darwinex/dwx-zeromq-connector#56]
HI,
I can't communicate with mt4 in any way. Any command I try to send I always receive this error message having activated socket monitoring.
I installed python anaconda and followed all the described procedures but I can't understand what the problem is.
Any suggestions?
<img width="740" alt="Schermata 2019-11-19 alle 20 07 03" src="https://user-images.githubusercontent.com/5798858/69177684-4d22ed80-0b08-11ea-960c-0d4b87b79d01.png">

**Comment by BobbyJobling** [comment]
Have you tried restarting MT4 after getting the error msg in Phyton? After MT4 restarts It works for me.

Sent from Yahoo Mail on Android 
 
  On Tue, 19 Nov 2019 at 19:09, ildeb<notifications@github.com> wrote:   
HI,
I can't communicate with mt4 in any way. Any command I try to send I always receive this error message having activated socket monitoring.
I installed python anaconda and followed all the described procedures but I can't understand what the problem is.
Any suggestions?

**Comment by ildeb** [comment]
Hi @BobbyJobling,
thank you for your quick reply, I tried to do as you suggested but the situation didn't change much. Now monitor socket debug messages appear continuously, as shown in the attached image, but if I send a command there is always the error that appeared before.
<img width="746" alt="Schermata 2019-11-19 alle 21 24 40" src="https://user-images.githubusercontent.com/5798858/69194056-7d7a8400-0b28-11ea-9fca-d78c26a3e19f.png">

**Comment by BobbyJobling** [comment]
When you restart MT4 the repeated event connect msg should eventually stop and indicate that PUSH and PULL connected successful. Did you get that or did the error msg carried on as in the image you posted?

Sent from Yahoo Mail on Android 
 
  On Tue, 19 Nov 2019 at 22:58, ildeb<notifications@github.com> wrote:   
Hi @BobbyJobling,
thank you for your quick reply, I tried to do as you suggested but the situation didn't change much. Now monitor socket debug messages appear continuously, as shown in the attached image, but if I send a command there is always the error that appeared before.

**Comment by ildeb** [comment]
Hi @BobbyJobling,
Those messages appear when I restart MT4 and scroll continuously. I tried again by disabling the debug logs, in this case if I send a new trade command, the first time nothing appears, the second time it displays the error: "Resource timeout ... please try again."
<img width="585" alt="Schermata 2019-11-20 alle 10 33 28" src="https://user-images.githubusercontent.com/5798858/69228317-a3814200-0b83-11ea-866a-9aeb0e8f9a1d.png">

**Comment by ildeb** [comment]
I solved by reinstalling the **MS VC ++ Libraries** again
