### ISSUE TITLE
The orders sent are opened and closed abruptly 

### ISSUE THREAD

**Issue by ildeb** [darwinex/dwx-zeromq-connector#60]
Hi,
when I send a trade order, the SL and TP cannot set or receive the data and remain at zero. After a few seconds MT4 automatically closes the newly opened order but I can't see any error in the logs.

**Construct Trade:**
`{'_action': 'OPEN', '_comment': 'DWX', '_type': 1, '_symbol': 'USDCHF', '_price': '0.99868', '_SL': '1.00679', '_TP': '0.98628', '_lots': 0.09, '_magic': 227059, '_ticket': 0}`

**MT4 Journal:**

```
2019.11.28 23:56:39.598	'30342778': order sell market 0.09 USDCHF sl: 0.00000 tp: 0.00000
2019.11.28 23:56:40.208	'30342778': order was opened : #168755843 sell 0.09 USDCHF at 0.99851 sl: 0.00000 tp: 0.00000
2019.11.28 23:56:40.286	'30342778': close order #168755843 sell 0.09 USDCHF at 0.99851 sl: 0.00000 tp: 0.00000 at price 0.00000
2019.11.28 23:56:40.895	'30342778': order #168755843 sell 0.09 USDCHF at 0.99851 sl: 0.00000 tp: 0.00000 closed at price 0.99861
```

**Comment by BobbyJobling** [comment]
Sent from Yahoo Mail on Android 
 
  On Thu, 28 Nov 2019 at 23:46, ildeb<notifications@github.com> wrote:   
Hi,
when I send a trade order, the SL and TP cannot set or receive the data and remain at zero. After a few seconds MT4 automatically closes the newly opened order but I can't see any error in the logs.

Construct Trade:
{'_action': 'OPEN', '_comment': 'DWX', '_type': 1, '_symbol': 'USDCHF', '_price': '0.99868', '_SL': '1.00679', '_TP': '0.98628', '_lots': 0.09, '_magic': 227059, '_ticket': 0}

MT4 Journal:
2019.11.28 23:56:39.598	'30342778': order sell market 0.09 USDCHF sl: 0.00000 tp: 0.00000
2019.11.28 23:56:40.208	'30342778': order was opened : #168755843 sell 0.09 USDCHF at 0.99851 sl: 0.00000 tp: 0.00000
2019.11.28 23:56:40.286	'30342778': close order #168755843 sell 0.09 USDCHF at 0.99851 sl: 0.00000 tp: 0.00000 at price 0.00000
2019.11.28 23:56:40.895	'30342778': order #168755843 sell 0.09 USDCHF at 0.99851 sl: 0.00000 tp: 0.00000 closed at price 0.99861

**Comment by pwerspire** [comment]
Hi,

The SL and TP should be in points, that's why the SL and TP are not valid.

I also wanted to be able to send it like that with values and tried to change the code in the metatrader but I couldn't get it to work

**Comment by integracore2** [comment]
Hi @ildeb,

As @pwerspire mentioned, SL and TP values need to be set in points, yes.

This was programmed this way to support any asset class as well as to promote flexibility -> e.g. so traders don't have to necessarily request the latest price first in order to set an appropriate SL/TP.

The MQL Server EA receives the SL/TP values in points and handles the execution accordingly.
