### ISSUE TITLE
Error whilst compiling the DWX_ZeroMQ_Service_v1.0.0.mq5

### ISSUE THREAD

**Issue by Pejhan** [darwinex/dwx-zeromq-connector#62]
I tried to move forward with the MT5 version scripts and so far I havent moved any where further than compiling the DWX_ZeroMQ_Service_v1.0.0.mq5 service. It mentions the following errors in file ZmqMsg.mqh:
![image](https://user-images.githubusercontent.com/2239224/71313568-d1da9180-244f-11ea-8621-e789a48fa35e.png)
which is sth on the lines of:
![image](https://user-images.githubusercontent.com/2239224/71313577-f0d92380-244f-11ea-9f6a-5849a4b7b615.png)
bear in mind that I have Zero experience in MQL but am willing to pull on any thread if doable.

**Comment by integracore2** [comment]
Hi @Pejhan,

Thank you for your interest in the project 🙂 

We currently have the MT5 version in beta-testing, hence are not providing support here for it.

As soon as we have a release data, we'll update the GitHub repo accordingly.
