### ISSUE TITLE
DWX_ZeroMQ_Server_v2.0.1_RC8 Compile Error

### ISSUE THREAD

**Issue by rafaelbate** [darwinex/dwx-zeromq-connector#63]

**Comment by chand2020** [comment]
Rafaelbate, Is your issue resolved? I have same error. Removed '&' sign and compiled successfully but getting library file can't open error after that. Please help. Thank you.

**Comment by rafaelbate** [comment]
Hello, it is, just use that file instead. Solved for me.

chand2020 <notifications@github.com> escreveu no dia sexta, 27/12/2019 à(s)
18:34:

**Comment by chand2020** [comment]
Thank you..
