### ISSUE TITLE
[Bug] Incorrect Logic for Publishing Market Ticks

### ISSUE THREAD

**Issue by octopyth** [darwinex/dwx-zeromq-connector#65]
The mechanism used for capturing ticks is based on the onTick method in MQL. This means that if the expert advisor is attached to EURUSD for example, the time stamp for capturing ticks will only be accurate for EURUSD. All the other symbols report the BID/ASK quotes at that particular time, so the number of ticks and the Timestamps for other symbols than EURUSD is completely inaccurate. Here is an example with USDCAD. As you can see It is registered as a tick, while the BID/ASK are the same:
![image](https://user-images.githubusercontent.com/640759/73677820-5a875700-46b7-11ea-886c-0b2ce3f3c10b.png)

**Comment by integracore2** [comment]
Hi @octopyth,

Thank you for raising this 👍 

Yes we're aware of this issue and already working on a patch for release soon.

Many thanks for your interest in the project - much appreciated!

**Comment by eabase** [comment]
@integracore2 
Any updates?

**Comment by elvinex** [comment]
Hi,
To my knowledge there is no way to get the exact time of a tick for other symbols than the chart symbol. 
However, the current version uses the OnTimer() function to check prices regularly. Therefore, the delay should be relatively small. You can determine the update frequency with the parameter `MILLISECOND_TIMER_PRICES`.
