### ISSUE TITLE
Metatrader 5

### ISSUE THREAD

**Issue by taleslimaf** [darwinex/dwx-zeromq-connector#66]
I would like to know if you have any plans to work on Metatrade 5. Any date for that to happen?

**Comment by VladPerervenko** [comment]
https://www.mql5.com/en/forum/333185

**Comment by integracore2** [comment]
Hi @taleslimaf,

Thank you for your interest in the project 🙂 

Yes, we do have a MetaTrader 5 version in beta-testing at the present time.

As soon as we have a release date, we'll update the GitHub repo.

Many thanks!
