### ISSUE TITLE
Send alert notification to python

### ISSUE THREAD

**Issue by santi2fx** [darwinex/dwx-zeromq-connector#69]
Please advice me, I want to send data terminal from notification mt4/mt5 go to python.

**Comment by integracore2** [comment]
Hi @santi2fx,

You would need to customize the MQL server EA to achieve this functionality:
https://github.com/darwinex/dwx-zeromq-connector/blob/master/v2.0.1/mql4/DWX_ZeroMQ_Server_v2.0.1_RC8.mq4

We don't plan on adding terminal notifications at the present time, but if you develop a working patch for notifications, please do feel free to submit a Pull Request and we'll be more than happy to review and commit.

All the best!
