### ISSUE TITLE
subscribe data has no response

### ISSUE THREAD

**Issue by hydrali** [darwinex/dwx-zeromq-connector#7]
Hello, 
Thanks a lot for writing this amazing library.
I have tried to follow the tutorial, and I can successfully place and close orders through python spyder meaning python and MT4 are successfully connected. Yet when I tried to subscribe to market data there's no response. I've made sure it's not the verbose issue. I can also see clearly in the MT4 experts window the prices are publishing constantly.

_zmq._DWX_MTX_SUBSCRIBE_MARKETDATA_(_symbol = 'EURUSD')
[KERNEL] Subscribed to EURUSD BID/ASK updates. See self._Market_Data_DB.

_zmq._Market_Data_DB.keys()
Out[44]: dict_keys([])

_zmq._Market_Data_DB
Out[45]: {}

![image](https://user-images.githubusercontent.com/26300697/56492974-0f34fb00-6520-11e9-933b-2e2e91be0ec3.png)

Thanks for helping

**Comment by codingsett** [comment]
same here

**Comment by codingsett** [comment]
![image](https://user-images.githubusercontent.com/27306293/56701798-7e217800-6709-11e9-89c5-4cede7bd3409.png)

Got it working so make sure your EA is smiling and inorder to print on python while the dictionary is being updated use a while loop to print out the data or make verbose=True then you are good to go.

**Comment by integracore2** [comment]
Hi @codingsett and @hydrali !

@codingsett - Thank you for providing the solution to @hydrali, great community spirit! 👏 

After several issue requests pointing to the same thing, we've updated the default value **_verbose=True** in the class **__init__** function to avoid any confusion going forward.

This verbosity flag simply prints JSON exchange in the console when set to True.

Regardless of its status (True or False), all output is stored in self._thread_data_output at all times, so no worries either way 👍

**Comment by moneyrolling** [comment]
Hi, may I know do anyone still any using this library, i am having the same issues despite the _verbose is set to true and live trading allowed, anyone can offer help? thanks

**Comment by VISFS98** [comment]
I have the same problem, when I subscribe to marketdata i get the next response:

![image](https://user-images.githubusercontent.com/56851528/116148736-92762200-a6e1-11eb-8e67-616442c718be.png)
