### ISSUE TITLE
`_DWX_MTX_SUBSCRIBE_MARKETDATA_` constantly print out bid/ask info.

### ISSUE THREAD

**Issue by hayyyyyyden** [darwinex/dwx-zeromq-connector#70]
I'm following your tutorials (it's a great tutorial btw, thx!), everything's good, except one thing is that
when I `_DWX_MTX_SUBSCRIBE_MARKETDATA_` to a symbol, it constantly print out the price info from metatrader, instead of just storing it in the background like what you showed in the [tutorial](https://www.youtube.com/watch?v=9EaP_7sSzEI&list=PLv-cA-4O3y94ygY4qDlfCcDqkMmqMteah&index=3).

<img width="852" alt="screenshot" src="https://user-images.githubusercontent.com/6135847/77336863-3e7d6900-6d7c-11ea-88cf-41c87f2dbd27.png">

This is happening when I set the `Publish_MarketData` to true in metatrader.

However,  if I set the `Publish_MarketData` to `false`, I can not get any data in the python client.

How can I change this "print out" behavior? I just want to get the realtime data in the code, to be used in my trading strategy.

**Comment by integracore2** [comment]
Hi @hayyyyyyden,

Thank you for your kind comments and feedback - much appreciated! 🙂 

Yes, you can do this by setting `_verbose=False` when initializing the class object.
