### ISSUE TITLE
[Enhancement Request] Provide a requirements.txt file to install the Python dependencies.

### ISSUE THREAD

**Issue by metaperl** [darwinex/dwx-zeromq-connector#71]
I propose that a `requirements.txt` file be in https://github.com/darwinex/dwx-zeromq-connector/tree/master/v2.0.1/python/api and the `README.md` updated to instruct users to type `pip install -r requirements.txt` to install the dependencies.

# contents of requirements.txt

zmq
pandas

**Comment by integracore2** [comment]
Thank you for pointing this out @metaperl 🙂 

We'll add this right away - many thanks for all your contributions, much appreciated!

**Comment by integracore2** [comment]
Done!
