### ISSUE TITLE
Function library for Javascript connection?

### ISSUE THREAD

**Issue by kantdonothin** [darwinex/dwx-zeromq-connector#73]
I am currently wanting to code an Algo for mt4 in Javascript. I cannot find a library that has all the functions (open orders, execute buy/sell, close orders, etc....) in javascript. i don't want to have to wrap every message in JSON everytime i want the system to do anything.

**Comment by integracore2** [comment]
Hi @kantdonothin,

Interesting approach trying to use Javascript 🙂 

You could develop a client application in Javascript that sends orders formatted such that the MQL server EA can parse, execute and respond:
https://github.com/darwinex/dwx-zeromq-connector/blob/master/v2.0.1/mql4/DWX_ZeroMQ_Server_v2.0.1_RC8.mq4

This project doesn't unfortunately serve a Javascript based solution - but hopefully the information above proves useful.

All the best!
