### ISSUE TITLE
ZeroMQ Connector fails to send orders with lot size > 0.01

### ISSUE THREAD

**Issue by hoangson0409** [darwinex/dwx-zeromq-connector#74]
Hi, I was trying to send orders using ZeroMQ Connector. It works fine for every order with lot size of 0.01, however did not manage to send any orders with lot size greater than above mentioned. 
I already tried changing the input parameters for EA on Metatrader MaximumLotSize to 1, but so far it still cannot send a 0.02lot orders.

Here is a picture of server reply when I tried to send order of 0.02 lot
![so7](https://user-images.githubusercontent.com/48992834/79637415-9f486780-81a9-11ea-89c7-be16bcff04a8.png)

Here is my input parameters for MQL EA
![so8](https://user-images.githubusercontent.com/48992834/79637428-c2731700-81a9-11ea-9bf6-d7ee5433e8c3.png)

**Comment by elvinex** [comment]
Hi,
thanks for reporting this issue. It is difficult to help since I cannot replicate the error. Are you still experiencing it? 
Also, are you using a Darwinex MT4 terminal? We have only tested the zeromq connector with Darwinex.
