### ISSUE TITLE
Adding an example showing how to work with indicators inside the strategy file on a different time frames

### ISSUE THREAD

**Issue by Nariman-Git** [darwinex/dwx-zeromq-connector#78]
It would be great if you could add one simple python example to show how to integrate an indicator inside the strategy file and make a trading decision based on that? Something similar to the existing Coin Flip Trader, but, incorporating at least one indicator operating on a , for instance, 15 min time frame ticker. 

Very much appreciated for being such helpful

**Comment by 1Eve** [comment]
I would love that inorder to use zeromq_connector to code my strategies which involve indicators available in MT4

**Comment by elvinex** [comment]
Hi,
generally there are two ways. Either you could calulate it in python from the price data you stored, for example using the [resample function ](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.resample.html) on a pandas data frame. 
Or you could do it in mql and pass the information via the socket connection similar to how it is done for example for DWX_GetOpenOrders(). 
However, this would be quite a lot of work. If a strategy is based mostly on technical indicators, I would highly recommend just to code it in mql4 and execute it directly in MT4.
