### ISSUE TITLE
dwx_zeroMQ_server_v2.0.1_RC8 fail to compile

### ISSUE THREAD

**Issue by farhadc7** [darwinex/dwx-zeromq-connector#85]
when i compile the file i face below errors:
'create' - function not defined	GlobalVariable.mqh	211	34
'::' - unexpected token	GlobalVariable.mqh	211	32

**Comment by Prhmma** [comment]
> 
> 
> when i compile the file i face below errors:
> 'create' - function not defined GlobalVariable.mqh 211 34
> '::' - unexpected token GlobalVariable.mqh 211 32

I have the exact same problem with dwx_zeroMQ_server_v2.0.1_RC8 and dwx_zeroMQ_server_v2.0.2_RC1
I tried to compile GlobalVariable.mqh separately and everything looks fine, but I can't compile the desired mq4 script.

**Comment by dirkjacobus** [comment]
I ran into the same issue. 

I resolved this by updating the dependencies from the mql-zmq repo directly (https://github.com/dingmaotu/mql-zmq).

Good luck!

**Comment by Prhmma** [comment]
> 
> 
> I ran into the same issue.
> 
> I resolved this by updating the dependencies from the mql-zmq repo directly (https://github.com/dingmaotu/mql-zmq).
> 
> Good luck!

It works fine now, thank you.
should we submit an issue for this so we can resolve this issue in this repo?

**Comment by farhadc7** [comment]
> > I ran into the same issue.
> > I resolved this by updating the dependencies from the mql-zmq repo directly (https://github.com/dingmaotu/mql-zmq).
> > Good luck!
> 
> It works fine now, thank you.
> should we submit an issue for this so we can resolve this issue in this repo?

i updated the code and now that works fine. thanks for your help.

**Comment by dirkjacobus** [comment]
@farhadc7 maybe we should leave this issue open until the authors update the dependencies within the repo itself.
