### ISSUE TITLE
Compile errors Metatrader 4 terminal build 1280

### ISSUE THREAD

**Issue by thomas795** [darwinex/dwx-zeromq-connector#88]
after upgrading to Metatrader terminal 4 build 1280 the Zero MQ implementation from Darwinx (DWX_ZeroMQ_Server_v2.0.1_RC8.mq4) project will no longer compile. i receive this error:

'::' - unexpected token	GlobalVariable.mqh	 in line 200
'create' - function not defined	GlobalVariable.mqh	in line 200
'::' - unexpected token	GlobalVariable.mqh	 in line 211
'create' - function not defined	GlobalVariable.mqh	 in line 211

Please help! :)

**Comment by Adolfo2978** [comment]
Hello I have the same problem as a solution thanks

**Comment by kmels** [comment]
was fixed here: https://github.com/dingmaotu/mql-zmq/commit/981394b9e91467256c060a03d5059548f4f6cf8a

To fix: just download and replace the newest `Include/Mql/GlobalVariable.mqh` and `Include/Zmq/Context.mqh` files

**Comment by thomas795** [comment]
Thanks alot kmels that worked! :)

**Comment by Martian4x** [comment]
Hello, I coped the files and on compile I got another error. Can you help?
![tempsnip](https://user-images.githubusercontent.com/61208727/88972030-9d6c6500-d2bd-11ea-9fd9-83ff71cb8ba7.png)

**Comment by thomas795** [comment]
Martian4x this is what helped me:

https://github.com/dingmaotu/mql4-lib/issues/54

the answer from 7iW. I copied all the mql4-lib include folders.
