### ISSUE TITLE
Compiling errors in GlobalVariable.mqh

### ISSUE THREAD

**Issue by scratch222** [darwinex/dwx-zeromq-connector#89]
'::' - unexpected token
200      if(!m_cs.isValid()) m_ref=HandleManager::create();

'create' - function not defined
200      if(!m_cs.isValid()) m_ref=HandleManager::create();

'::' - unexpected token
211      m_ref=HandleManager::create();

'create' - function not defined
211      m_ref=HandleManager::create();

'&' - parameter passed as reference, variable expected
206      InterpretZmqMessage(&pushSocket, components);

**Comment by Mtype** [comment]
Same here. I used to had it running flawlessly. Did a modification / upgrade today then I'm getting the same message.

**Comment by scratch222** [comment]
> 
> 
> Same here. I used to had it running flawlessly. Did a modification / upgrade today then I'm getting the same message.
> 
> Edit _ This solution worked:
> 
> 7iW commented 4 days ago
> I was able to resolve this issue by replacing the Darwinex Zero MQ implementation with the Zero MQ implementation from https://github.com/dingmaotu/mql-zmq.

That worked thanks.

**Comment by elvinex** [comment]
Hi,
thank you for raising this issue. Indeed the update required some changes in the dependencies. The file mql-zmq-master.zip was updated in our repo, so it should work again now without the need to download it from the original source.
