### ISSUE TITLE
Market Data Subscription: command does not reach MT4 Server, Order does

### ISSUE THREAD

**Issue by aquaandi** [darwinex/dwx-zeromq-connector#9]
I'm on Windows 10, connecting via 
_zmq = DWX_ZeroMQ_Connector(_verbose=True)
_zmq._DWX_MTX_SUBSCRIBE_MARKETDATA_(_symbol='EURUSD')

then waiting via a timer in a thread for print(_zmq._Market_Data_DB) to update, but I get no data.

In the class and method
DWX_ZeroMQ_Connector
def _DWX_MTX_SUBSCRIBE_MARKETDATA_(self, _symbol, _string_delimiter=';'):

this code never gets called when I subscribe to market data:
self._MarketData_Thread = Thread(target=self._DWX_ZMQ_Poll_Data, args=(_string_delimiter))
self._MarketData_Thread.start()

Also the MT4 server only receives messages (in void InterpretZmqMessage(...)) when I order (which it executes fine), but not when I subscribe to market data, or request all open trades.

I installed a couple different versions and libraries I thought were related, but weren't. So maybe it's .dlls?

**Comment by hartungalex24** [comment]
I have the same problem. 

I see MT4 server is publishing in experts terminal. But I am left with an empty dictionary on the python side.  Also the:
self._MarketData_Thread = Thread(target=self._DWX_ZMQ_Poll_Data, args=(_string_delimiter))
self._MarketData_Thread.start()

is not getting called.

**Comment by integracore2** [comment]
> I'm on Windows 10, connecting via
> _zmq = DWX_ZeroMQ_Connector(_verbose=True)
> _zmq._DWX_MTX_SUBSCRIBE_MARKETDATA_(_symbol='EURUSD')
> 
> then waiting via a timer in a thread for print(_zmq._Market_Data_DB) to update, but I get no data.
> 
> In the class and method
> DWX_ZeroMQ_Connector
> def _DWX_MTX_SUBSCRIBE_MARKETDATA_(self, _symbol, _string_delimiter=';'):
> 
> this code never gets called when I subscribe to market data:
> self._MarketData_Thread = Thread(target=self._DWX_ZMQ_Poll_Data, args=(_string_delimiter))
> self._MarketData_Thread.start()
> 
> Also the MT4 server only receives messages (in void InterpretZmqMessage(...)) when I order (which it executes fine), but not when I subscribe to market data, or request all open trades.
> 
> I installed a couple different versions and libraries I thought were related, but weren't. So maybe it's .dlls?

Hi @aquaandi ,

1) Could you confirm that the EA is configured to publish market data? -> Publish_MarketData = True in Inputs?

2) As shown in the code you've pasted, the function **_DWX_MTX_SUBSCRIBE_MARKETDATA_** only calls the Thread creation code, if self._MarketData_Thread is None at the present time.

This thread is already initialized by the _init_() function when you create an instance of DWX_ZeroMQ_Connector, so you don't have to create it again, nor will the code.

3) The instructions exactly as detailed in README.md should get your environment working, therefore please only install the libraries stated in the README.

We recommend that users install the Anaconda distribution that ships with everything you need to simply download the Python script and get up and running.

**Comment by integracore2** [comment]
> I have the same problem.
> 
> I see MT4 server is publishing in experts terminal. But I am left with an empty dictionary on the python side. Also the:
> self._MarketData_Thread = Thread(target=self._DWX_ZMQ_Poll_Data, args=(_string_delimiter))
> self._MarketData_Thread.start()
> 
> is not getting called.

Hi @hartungalex24 ,

Please see https://github.com/darwinex/dwx-zeromq-connector/issues/9#issuecomment-492965260 as it relates to your query.

**Comment by integracore2** [comment]
Also @aquaandi and @hartungalex24 ,

Thank you so much for your feedback here 😃 

Every issue / bug / report helps us help you, and that helps everyone else who reads these too!

We are going to be recording a Video Tutorial soon on common issues and fixes that we've compiled from GitHub Issues - so stay tuned!

**Comment by integracore2** [comment]
Further to the last message here, we've updated the MQL Expert Advisor to fix a small bug in the code publishing functionality.

Kindly update your forks accordingly - thanks!

**Comment by hartungalex24** [comment]
@integracore2 Thank you so much for your reply. I have pulled the new source code for MQL4 EA and have made the modifications to the setup and call of the constructor as you mentioned. Please see my netstat report below: 

![image](https://user-images.githubusercontent.com/20324880/57868851-c0524c80-77d1-11e9-86c3-09b0a4ede4bc.png)

Still not receiving any data on the python side.

**Comment by aquaandi** [comment]
Thank you for the reply, for me the updated MT4 EA works. I'm now getting live data in python. I did however also do a reboot, which might have loaded newer .dlls

I don't currently have grep installed, but can if that helps.

**Comment by hartungalex24** [comment]
I got it working. After a restart on the machine and switching to PyCharm on an anaconda 3.7 ide I was able to get the ports properly setup and listening. 

![image](https://user-images.githubusercontent.com/20324880/57872121-f810c280-77d8-11e9-945c-fcd91287e523.png)

![image](https://user-images.githubusercontent.com/20324880/57872138-019a2a80-77d9-11e9-869d-000203ecf97e.png)

Thank you for all your help and for creating such an amazing tool!

**Comment by unesssaeed** [comment]
> Thank you for the reply, for me the updated MT4 EA works. I'm now getting live data in python. I did however also do a reboot, which might have loaded newer .dlls
> 
> I don't currently have grep installed, but can if that helps.

hey dude I have the same problem
may you share your solution?

**Comment by unesssaeed** [comment]
@hartungalex24 hi, may you share your solution cause my ports are on "stablished" yet
