### ISSUE TITLE
Litte bug  with some Pairs

### ISSUE THREAD

**Issue by osoluche** [darwinex/dwx-zeromq-connector#90]
In first place, let me said thank you for your great job, it's amazing,  in second place well .... let me explain this bug; 

In some pairs, not accept SL or TP, even with normalized values, such USDCHF, this is the json formatted with ordered_dict(), and supplied values:

{
'_action': 'OPEN', 
'_type': 0, 
'_symbol': 'USDCHF', 
'_price': 0.0, 
'_SL': 0.91541, 
'_TP': 0.92501,
 '_comment': 'Darwinex Test, 
'_lots': 0.01, 
'_magic': 123456, 
'_ticket': 0
}
In console catch fine

DWX_ZeroMQ_Server_v2.0.1_RC8
TRADE;OPEN;0;USDCHF;0.0;0.91541;0.92501;Darwinex Test;0.01;123456;0

But when execute, not take the submitted values:

![Screen Shot 2020-08-11 at 22 25 08](https://user-images.githubusercontent.com/759204/89971667-84e73d80-dc21-11ea-93d8-62f553486b29.png)

Check on EURUSD = OK,
Check on CADJPY = OK

Thanks again & grettings;

**Comment by elvinex** [comment]
Hi,
thank you very much for your feedback. There was indeed a NormalizeDouble() call missing in the mql4 code. 

There is currently also an inconsistency in how the SL and TP are set (relative or absolute). We will soon publish an update where both, the new order and the modify function, will use relative SL and TP values.
