### ISSUE TITLE
Not having full options in inputs tab

### ISSUE THREAD

**Issue by mrhajbabaei** [darwinex/dwx-zeromq-connector#94]
Hi. I just add the dwx expert to my MT4, but I have not whole options just like the photo on the tutorial. My options are just like this:
![image](https://user-images.githubusercontent.com/25500417/94535114-09cbfc00-024e-11eb-89b0-58b3660637af.png)
(as you can see, "t1" & "Publish_MarketData" options have not appeared)
Has anybody ever experienced this problem?

**Comment by elvinex** [comment]
Hi,
the tutorial was made with an older version of the zeromq-connector. Some of the open parameters have changed. For example, Publish_MarketData is now hidden because it is set automatically if you send a market data request via a python script.
