### ISSUE TITLE
Could not connect MT4 to the IPython console, Exception Type KeyError. Args

### ISSUE THREAD

**Issue by Michael5531** [darwinex/dwx-zeromq-connector#95]
Hi there,

I am following the steps listed on the blogs, and successfully deployed the order. However, once trying to get the order status or release the order, something went wrong in my IPython console.

Exception Type KeyError. Args:
('_action',)

Regards.

**Comment by elvinex** [comment]
Hi,

thank you for raising this issue. What function did you use to get the order status? 
After using _DWX_MTX_NEW_TRADE_() to open a new trade, you should be able to get the list of all open trades by calling _DWX_MTX_GET_ALL_OPEN_TRADES_().

**Comment by Michael5531** [comment]
Hi, 

I figured out that I am not allowing auto trading for MT4. Since reopen it everything goes fine :)))

Thanks for your reply!

**Comment by elvinex** [comment]
Ok, great, thanks for letting us know the reason.
