### ISSUE TITLE
'=' - type mismatch GlobalVariable.mqh 292 12

### ISSUE THREAD

**Issue by TheChapus** [darwinex/dwx-zeromq-connector#96]
Hello,
I was using mql-zmq for quite some time, I made a change in the dwx-zeromq code and I have an error in GlobalVariable, exactly on line 292:
m_hm = new HM;
I have downloaded the whole folder again from this repository and replaced all the files and still have the same problem

My mt4 version is: 4.0 Build 1280 July 24, 2020

**Comment by elvinex** [comment]
Hi,
It seems that the error is in your code. I don't see a line "m_hm = new HM;" in the DWX_ZeroMQ_Server_v2.0.1_RC8.mq4 file. So it probably is not connected to the dwx-zeromq-connector.

**Comment by TheChapus** [comment]
First of all thank you very much for your reply.

I just checked my error, forgot to replace the * .dll files

Now compiles perfectly

**Comment by elvinex** [comment]
Ok, great to hear that it works now. :)
