### ISSUE TITLE
Errors when compile DWX_ZeroMQ_Server_v2.0.1_RC8.mq4 

### ISSUE THREAD

**Issue by saeedalghamdi** [darwinex/dwx-zeromq-connector#99]
Greetings,

I compiled the DWX_ZeroMQ_Server_v2.0.1_RC8.mq4 and received the following errors:
'create' - function not defined	GlobalVariable.mqh	 200	 48
'::' - unexpected token	GlobalVariable.mqh	211	32
'create' - function not defined	GlobalVariable.mqh	211	34

regards,

**Comment by elvinex** [comment]
Hi,
did you download the latest version and replaced all dependencies with the files from the latest version?

**Comment by TheSnowGuru** [comment]
It can be easier to connect to metatrader4 with lot's of features with this framework, goodluck.
https://github.com/TheSnowGuru/PyTrader-python-mt4-mt5-trading-api-connector-drag-n-drop/

**Comment by SpideyAntman** [comment]
Update all dependencies from latest files. It should be good after that
